[2025-09-24T21:20:48.863+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-24T21:20:48.892+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecom_etl.ingest_to_mongo scheduled__2025-09-23T02:30:00+00:00 [queued]>
[2025-09-24T21:20:48.898+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecom_etl.ingest_to_mongo scheduled__2025-09-23T02:30:00+00:00 [queued]>
[2025-09-24T21:20:48.900+0000] {taskinstance.py:2306} INFO - Starting attempt 5 of 5
[2025-09-24T21:20:48.916+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): ingest_to_mongo> on 2025-09-23 02:30:00+00:00
[2025-09-24T21:20:48.921+0000] {standard_task_runner.py:63} INFO - Started process 421 to run task
[2025-09-24T21:20:48.925+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecom_etl', 'ingest_to_mongo', 'scheduled__2025-09-23T02:30:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/ecom_etl_dag.py', '--cfg-path', '/tmp/tmpy9g_2xlf']
[2025-09-24T21:20:48.928+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask ingest_to_mongo
[2025-09-24T21:20:48.993+0000] {task_command.py:426} INFO - Running <TaskInstance: ecom_etl.ingest_to_mongo scheduled__2025-09-23T02:30:00+00:00 [running]> on host b829da94a7fc
[2025-09-24T21:20:49.067+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ecom' AIRFLOW_CTX_DAG_ID='ecom_etl' AIRFLOW_CTX_TASK_ID='ingest_to_mongo' AIRFLOW_CTX_EXECUTION_DATE='2025-09-23T02:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-23T02:30:00+00:00'
[2025-09-24T21:20:49.068+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-24T21:20:49.087+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-24T21:20:49.088+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'export MONGO_HOST=mongo MONGO_USER=ecom_admin MONGO_PASS=ecom_admin_pass MONGO_DB=ecom;python /opt/airflow/scripts/ingest_to_mongo.py']
[2025-09-24T21:20:49.097+0000] {subprocess.py:86} INFO - Output:
[2025-09-24T21:20:50.306+0000] {subprocess.py:93} INFO - Loading olist_customers_dataset.csv -> customers ...
[2025-09-24T21:20:50.306+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-09-24T21:20:50.307+0000] {subprocess.py:93} INFO -   File "/opt/airflow/scripts/ingest_to_mongo.py", line 48, in <module>
[2025-09-24T21:20:50.309+0000] {subprocess.py:93} INFO -     load_csv_to_mongo("olist_customers_dataset.csv", "customers", index_field="customer_id")
[2025-09-24T21:20:50.310+0000] {subprocess.py:93} INFO -   File "/opt/airflow/scripts/ingest_to_mongo.py", line 35, in load_csv_to_mongo
[2025-09-24T21:20:50.312+0000] {subprocess.py:93} INFO -     df = pd.read_csv(path)
[2025-09-24T21:20:50.313+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^^
[2025-09-24T21:20:50.313+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
[2025-09-24T21:20:50.314+0000] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2025-09-24T21:20:50.314+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-24T21:20:50.314+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
[2025-09-24T21:20:50.315+0000] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2025-09-24T21:20:50.315+0000] {subprocess.py:93} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-24T21:20:50.315+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
[2025-09-24T21:20:50.316+0000] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2025-09-24T21:20:50.316+0000] {subprocess.py:93} INFO -                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-24T21:20:50.316+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
[2025-09-24T21:20:50.316+0000] {subprocess.py:93} INFO -     self.handles = get_handle(
[2025-09-24T21:20:50.317+0000] {subprocess.py:93} INFO -                    ^^^^^^^^^^^
[2025-09-24T21:20:50.317+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
[2025-09-24T21:20:50.317+0000] {subprocess.py:93} INFO -     handle = open(
[2025-09-24T21:20:50.318+0000] {subprocess.py:93} INFO -              ^^^^^
[2025-09-24T21:20:50.318+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: 'data/raw/olist_customers_dataset.csv'
[2025-09-24T21:20:50.920+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-24T21:20:50.921+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-24T21:20:50.928+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-24T21:20:50.933+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ecom_etl, task_id=ingest_to_mongo, run_id=scheduled__2025-09-23T02:30:00+00:00, execution_date=20250923T023000, start_date=20250924T212048, end_date=20250924T212050
[2025-09-24T21:20:50.948+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 13 for task ingest_to_mongo (Bash command failed. The command returned a non-zero exit code 1.; 421)
[2025-09-24T21:20:50.992+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-24T21:20:51.004+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-24T21:20:51.005+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
