[2025-09-24T21:05:29.778+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-24T21:05:29.803+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecom_etl.ingest_to_mongo manual__2025-09-24T21:05:25.706196+00:00 [queued]>
[2025-09-24T21:05:29.808+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecom_etl.ingest_to_mongo manual__2025-09-24T21:05:25.706196+00:00 [queued]>
[2025-09-24T21:05:29.809+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-24T21:05:29.826+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): ingest_to_mongo> on 2025-09-24 21:05:25.706196+00:00
[2025-09-24T21:05:29.831+0000] {standard_task_runner.py:63} INFO - Started process 101 to run task
[2025-09-24T21:05:29.835+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecom_etl', 'ingest_to_mongo', 'manual__2025-09-24T21:05:25.706196+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/ecom_etl_dag.py', '--cfg-path', '/tmp/tmpswwzlkax']
[2025-09-24T21:05:29.837+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask ingest_to_mongo
[2025-09-24T21:05:29.897+0000] {task_command.py:426} INFO - Running <TaskInstance: ecom_etl.ingest_to_mongo manual__2025-09-24T21:05:25.706196+00:00 [running]> on host b829da94a7fc
[2025-09-24T21:05:29.982+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ecom' AIRFLOW_CTX_DAG_ID='ecom_etl' AIRFLOW_CTX_TASK_ID='ingest_to_mongo' AIRFLOW_CTX_EXECUTION_DATE='2025-09-24T21:05:25.706196+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-24T21:05:25.706196+00:00'
[2025-09-24T21:05:29.983+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-24T21:05:30.002+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-24T21:05:30.003+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'export MONGO_HOST=mongo MONGO_USER=ecom_admin MONGO_PASS=ecom_admin_pass MONGO_DB=ecom;python /opt/airflow/scripts/ingest_to_mongo.py']
[2025-09-24T21:05:30.012+0000] {subprocess.py:86} INFO - Output:
[2025-09-24T21:05:31.247+0000] {subprocess.py:93} INFO - Loading olist_customers_dataset.csv -> customers ...
[2025-09-24T21:05:31.247+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-09-24T21:05:31.248+0000] {subprocess.py:93} INFO -   File "/opt/airflow/scripts/ingest_to_mongo.py", line 43, in <module>
[2025-09-24T21:05:31.250+0000] {subprocess.py:93} INFO -     load_csv_to_mongo("olist_customers_dataset.csv", "customers", index_field="customer_id")
[2025-09-24T21:05:31.251+0000] {subprocess.py:93} INFO -   File "/opt/airflow/scripts/ingest_to_mongo.py", line 30, in load_csv_to_mongo
[2025-09-24T21:05:31.254+0000] {subprocess.py:93} INFO -     df = pd.read_csv(path)
[2025-09-24T21:05:31.254+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^^
[2025-09-24T21:05:31.255+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
[2025-09-24T21:05:31.255+0000] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2025-09-24T21:05:31.255+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-24T21:05:31.256+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
[2025-09-24T21:05:31.256+0000] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2025-09-24T21:05:31.256+0000] {subprocess.py:93} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-24T21:05:31.257+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
[2025-09-24T21:05:31.257+0000] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2025-09-24T21:05:31.257+0000] {subprocess.py:93} INFO -                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-24T21:05:31.258+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
[2025-09-24T21:05:31.258+0000] {subprocess.py:93} INFO -     self.handles = get_handle(
[2025-09-24T21:05:31.258+0000] {subprocess.py:93} INFO -                    ^^^^^^^^^^^
[2025-09-24T21:05:31.259+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
[2025-09-24T21:05:31.259+0000] {subprocess.py:93} INFO -     handle = open(
[2025-09-24T21:05:31.259+0000] {subprocess.py:93} INFO -              ^^^^^
[2025-09-24T21:05:31.259+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: 'data/raw/olist_customers_dataset.csv'
[2025-09-24T21:05:31.820+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-24T21:05:31.821+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-24T21:05:31.826+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-24T21:05:31.829+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ecom_etl, task_id=ingest_to_mongo, run_id=manual__2025-09-24T21:05:25.706196+00:00, execution_date=20250924T210525, start_date=20250924T210529, end_date=20250924T210531
[2025-09-24T21:05:31.842+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task ingest_to_mongo (Bash command failed. The command returned a non-zero exit code 1.; 101)
[2025-09-24T21:05:31.853+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-24T21:05:31.867+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-24T21:05:31.868+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
